spring:
  application:
    name: soko-app

  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/soko_app

    jpa:
      hibernate:
        ddl-auto: update

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

    show-sql: true

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
   port: 8081

